### PR TITLE
officer updates for fall 2023

### PR DESCRIPTION
**Pull request by ryankbr**

### CODE REVIEW

**Review by ezrj — APPROVED** [review]
carol's picture is kinda low resolution. looks like a security cam picture they show in movies when they're like " she was last seen in Bolivia, 2013. * *slides picture across desk* *. Nobody's seen her since." and then she fights James Bond on top of the Louvre

**Comment by carolgeng** [comment]
> carol's picture is kinda low resolution. looks like a security cam picture they show in movies when they're like " she was last seen in Bolivia, 2013. * _slides picture across desk_ *. Nobody's seen her since." and then she fights James Bond on top of the Louvre

:c

**Comment by ezratamu** [comment]
> > carol's picture is kinda low resolution. looks like a security cam picture they show in movies when they're like " she was last seen in Bolivia, 2013. * _slides picture across desk_ *. Nobody's seen her since." and then she fights James Bond on top of the Louvre
> 
> :c

IMG_6499

**Comment by ezrj** [comment]
> > carol's picture is kinda low resolution. looks like a security cam picture they show in movies when they're like " she was last seen in Bolivia, 2013. * _slides picture across desk_ *. Nobody's seen her since." and then she fights James Bond on top of the Louvre
> 
> :c

IMG_6499

**Comment by carolgeng** [comment]
Bruh where'd that picture even come from I never took a pic like that lol

**Comment by ezrj** [comment]
Bolivia circa 2013 before you stole the Tesseract and went off the grid

**Review by peicasey — APPROVED** [review]
lgtm 👍

**Pull request merged**
